apiVersion: v1
kind: Pod
metadata:
  name: tsn-app-n1
  annotations:
    k8s.v1.cni.cncf.io/networks: flannel, tsncni 
  labels:
    app: tsn-app-n1
spec:
  containers:
  - name: tsn-perf-n1
    image: andreab1081/ktsnd:tsn-perf
    imagePullPolicy: IfNotPresent
    command: ["/bin/bash"]
    tty: true
    resources:
      limits:
        cpu: "2"
      requests:
        cpu: "2"
    securityContext:
      privileged: true
    volumeMounts:
    - name: dev-shm
      mountPath: /dev/shm
  volumes:
  - name: dev-shm
    hostPath:
      path: /dev/shm
      type: Directory
  hostNetwork: false # Equivalente a `--net=none`
  nodeSelector:
    kubernetes.io/hostname: node1

---

apiVersion: v1
kind: Pod
metadata:
  name: tsn-app-n2
  annotations:
    k8s.v1.cni.cncf.io/networks: flannel, tsncni
  labels:
    app: tsn-app-n2
spec:
  containers:
  - name: tsn-perf-n2
    image: andreab1081/ktsnd:tsn-perf
    imagePullPolicy: IfNotPresent
    command: ["/bin/bash"]
    tty: true
    resources:
      limits:
        cpu: "2"
      requests:
        cpu: "2"
    securityContext:
      privileged: true
    volumeMounts:
    - name: dev-shm
      mountPath: /dev/shm
  volumes:
  - name: dev-shm
    hostPath:
      path: /dev/shm
      type: Directory
  hostNetwork: false # Equivalente a `--net=none`
  nodeSelector:
    kubernetes.io/hostname: node2

