apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: flannel
  namespace: default
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "flannel",
      "type": "flannel",
      "delegate": {
        "isDefaultGateway": true,
        "hairpinMode": true,
        "ipMasq": true
      }
    }
