apiVersion: v1
kind: Pod
metadata:
  name: ktsnd-app-n1
  annotations:
    k8s.v1.cni.cncf.io/networks: '[{"name": "flannel"}, {"name": "tsncni"}]'
  labels:
    app: ktsnd-app
spec:
  containers:
  - name: ktsnd-n1
    image: andreab1081/ktsnd:ktsnd
    imagePullPolicy: IfNotPresent
    command: ["sleep", "infinity"]  # override entrypoint per settare a mano vhost0 corretto
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /dev/shm
      name: dev-shm
    - mountPath: /dev/hugepages
      name: dev-hugepages
    - mountPath: /usr/local/var/run/openvswitch
      name: var-run-openvswitch
    resources:
      limits:
        cpu: "4"
        hugepages-2Mi: 4096Mi
        memory: 4096Mi
      requests:
        cpu: "4"
        hugepages-2Mi: 4096Mi
        memory: 4096Mi
    env:
    - name: NO_NETWORK
      value: "true"
  - name: tsn-perf-n1
    image: andreab1081/ktsnd:tsn-perf-xe
    imagePullPolicy: IfNotPresent
    command: ["/bin/bash"]
    tty: true
    resources:
      limits:
        cpu: "2"
        hugepages-2Mi: 4096Mi
        memory: 2024Mi
      requests:
        cpu: "2"
        hugepages-2Mi: 4096Mi
        memory: 2024Mi
    env:
    - name: NETWORK_TYPE
      value: "flannel,tsncni"
    securityContext:
      privileged: true
    volumeMounts:
    - name: dev-shm
      mountPath: /dev/shm
  volumes:
  - name: dev-shm
    emptyDir:
      medium: Memory
  - name: dev-hugepages
    emptyDir:
      medium: HugePages
  - name: var-run-openvswitch
    hostPath:
      path: /usr/local/var/run/openvswitch
      type: Directory
  nodeSelector:
    kubernetes.io/hostname: node1

---

apiVersion: v1
kind: Pod
metadata:
  name: ktsnd-app-n2
  annotations:
    k8s.v1.cni.cncf.io/networks: '[{"name": "flannel"}, {"name": "tsncni"}]'
  labels:
    app: ktsnd-app-n2
spec:
  containers:
  - name: ktsnd-n2
    image: andreab1081/ktsnd:ktsnd
    imagePullPolicy: IfNotPresent
    command: ["sleep", "infinity"]  # override entrypoint per settare a mano vhost0 corretto
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /dev/shm
      name: dev-shm
    - mountPath: /dev/hugepages
      name: dev-hugepages
    - mountPath: /usr/local/var/run/openvswitch
      name: var-run-openvswitch
    resources:
      limits:
        cpu: "4"
        hugepages-2Mi: 4096Mi
        memory: 4096Mi
      requests:
        cpu: "4"
        hugepages-2Mi: 4096Mi
        memory: 4096Mi
    env:
    - name: NO_NETWORK
      value: "true"
  - name: tsn-perf-n2
    image: andreab1081/ktsnd:tsn-perf-xe
    imagePullPolicy: IfNotPresent
    command: ["/bin/bash"]
    tty: true
    resources:
      limits:
        cpu: "2"
        hugepages-2Mi: 4096Mi
        memory: 2024Mi
      requests:
        cpu: "2"
        hugepages-2Mi: 4096Mi
        memory: 2024Mi
    env:
    - name: NETWORK_TYPE
      value: "flannel,tsncni"
    securityContext:
      privileged: true
    volumeMounts:
    - name: dev-shm
      mountPath: /dev/shm
  volumes:
  - name: dev-shm
    emptyDir:
      medium: Memory
  - name: dev-hugepages
    emptyDir:
      medium: HugePages
  - name: var-run-openvswitch
    hostPath:
      path: /usr/local/var/run/openvswitch
      type: Directory
  nodeSelector:
    kubernetes.io/hostname: node2

